### PR TITLE
fix(browserCapabilities) bump minimum chrome version to 88

### PR DESCRIPTION
**Pull request by NewEraCracker**
This is the target chrome version in webpack babel

https://github.com/jitsi/lib-jitsi-meet/blob/3b38ab37f2bd2777d9ac56ee006840d412aac83e/webpack-shared-config.js#L47

### CODE REVIEW

**Comment by saghul** [comment]
I'd say let's bump it to 90. Then once ~110 hits we can bump it to 96 since it will be an LTS release: https://support.google.com/chrome/a/answer/11333726

**Comment by NewEraCracker** [comment]
I am more inclined to change this instead to 88. Our custom application still gets some mobile users on that version.

**Comment by saghul** [comment]
> I am more inclined to change this instead to 88. Our custom application still gets some mobile users on that version.

Sounds good.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by jallamsetty1** [comment]
Closing this since the plan is to bump the version to 96.

**Pull request closed without merging**
