### PR TITLE
The missing module.exports for JitsiDTMFManager was added

### PR DESCRIPTION
**Pull request by iScorpio**
This is fixing dtmf issue

### CODE REVIEW

**Comment by saghul** [comment]
Duplicate ot https://github.com/jitsi/lib-jitsi-meet/pull/867

**Comment by saghul** [comment]
@iScorpio can you please sign the CLA?

**Comment by iScorpio** [comment]
> @iScorpio can you please sign the CLA?

yes

**Comment by saghul** [comment]
Jenkins please test this please.

**Pull request merged**
