### PR TITLE
E2EE: Refactor JSDoc and Context test

### PR DESCRIPTION
**Pull request by NewEraCracker**
See both commits details.

### CODE REVIEW

**Comment by saghul** [comment]
Thanks! We have a couple of pending changes let's wait just in case any API needs changing.

**Comment by saghul** [comment]
Jenkins please test this please.

**Review by saghul — APPROVED** [review]

**Comment by tmoldovan8x8** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
Unrelated test failure. It was a page crash.

**Pull request merged**
