### PR TITLE
fix(types) update hand-crafted types

### PR DESCRIPTION
**Pull request by NewEraCracker**
Remove containsTrack method that has been removed by an earlier commit, and apply some types updates.

### CODE REVIEW

**Comment by sapkra** [comment]
If you want to, you can also go to [my repo](https://github.com/solydhq/lib-jitsi-meet) and create a PR with the updated types I created. Several types are outdated unfortunately but I didn't had time to compare them again and create a PR for this repo.

**Comment by saghul** [comment]
What branch should I pull from @sapkra ?

**Comment by NewEraCracker** [comment]
Leaving this as draft for the moment, until it can be tested or more parts of lib-jitsi-meet are converted to typescript.

**Comment by NewEraCracker** [comment]
I was able to test these changes and although this only updates types partially, it is better than nothing. I plan on submitting further updates once this PR is merged.

**Comment by saghul** [comment]
Jenkins please test this please.

**Review by saghul — DISMISSED** [review]

**Comment by NewEraCracker** [comment]
I have rebased this branch to latest upstream and reversed removal of e2ee worker types (previous version of this PR).

Please take a look.

**Review by saghul — APPROVED** [review]

**Pull request merged**
