### PR TITLE
Updated param comment

### PR DESCRIPTION
**Pull request by larspa**

### CODE REVIEW

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
@larspa Have you ran the linter? It should run automatically when you commit.

```
/home/jenkins/jitsi-meet/node_modules/lib-jitsi-meet/modules/RTC/JitsiTrack.js
   21:1  error  Line 21 exceeds the maximum line length of 80   max-len
   38:1  error  Line 38 exceeds the maximum line length of 80   max-len
  260:1  error  Line 260 exceeds the maximum line length of 80  max-len
  275:1  error  Line 275 exceeds the maximum line length of 80  max-len
  292:1  error  Line 292 exceeds the maximum line length of 80  max-len
```

**Comment by larspa** [comment]
> @larspa Have you ran the linter? It should run automatically when you commit.
> 
> ```
> /home/jenkins/jitsi-meet/node_modules/lib-jitsi-meet/modules/RTC/JitsiTrack.js
>    21:1  error  Line 21 exceeds the maximum line length of 80   max-len
>    38:1  error  Line 38 exceeds the maximum line length of 80   max-len
>   260:1  error  Line 260 exceeds the maximum line length of 80  max-len
>   275:1  error  Line 275 exceeds the maximum line length of 80  max-len
>   292:1  error  Line 292 exceeds the maximum line length of 80  max-len
> ```

I changed the things in github itself so maybe something went wrong?

**Comment by saghul** [comment]
> I changed the things in github itself so maybe something went wrong?

Please don't use GH to make changes. You'll skip the linter and won't know why things fail.

**Pull request closed without merging**
