### PR TITLE
feat: Enables the moderator to {dis/en}able bridge-side rtcstats.

### PR DESCRIPTION
**Pull request by gpolitis**

### CODE REVIEW

**Comment by damencho** [comment]
Will we disable and callstats when this is set?

**Comment by gpolitis** [comment]
> Will we disable and callstats when this is set?

We can, if we want to. Alternatively we can propagate a separate flag for callstats. I don't have a preference, so I'm open to suggestions :-)

**Comment by damencho** [comment]
Well if this is called rtcstatsEnabled, then we need to add and one for callstats.

**Comment by damencho** [comment]
Can you add one so we can do the same and for callstats, anyway you will do the dance with PRs in all projects, can you add to those PRs and callstats disabling. 
We already detect callstats. being disabled ...

**Comment by damencho** [comment]
https://github.com/gimre/lib-jitsi-meet/blob/c24130622ef3cf24078b0e5244a09e1d9c37dfd7/modules/statistics/statistics.js#L166

**Comment by gpolitis** [comment]
@damencho this is ready, could you please take a look?

**Review by damencho — APPROVED** [review]

**Comment by gpolitis** [comment]
@damencho I realized that the default in the client is actually `false` (the default in the config.js is misleading and I have opened a PR for that here https://github.com/jitsi/jitsi-meet/pull/10425) so I had to adjust this patch. Could you please take another look?

**Review by damencho — APPROVED** [review]

**Review by damencho — APPROVED** [review]

**Pull request merged**
