### PR TITLE
fix(SignalingLayer,TPC) do not set videoType for audio sources

### PR DESCRIPTION
**Pull request by NewEraCracker**
As implemented in other parts of the code, do not set videoType for audio sources.

Related to #1979

### CODE REVIEW

**Review by saghul — DISMISSED** [review]

**Comment by saghul** [comment]
The CI is unhappy.

**Comment by NewEraCracker** [comment]
Should be solved now.

A segunda, 15/05/2023, 13:43, Saúl Ibarra Corretgé ***@***.***>
escreveu:

**Review by saghul — APPROVED** [review]
@jallamsetty1 can you PTAL too?

**Review by jallamsetty1 — APPROVED** [review]
LGTM too!

**Pull request merged**
