### PR TITLE
Update README.md Resolve installation failure

### PR DESCRIPTION
**Pull request by daxiondi**
## install fail
i use node version 10 and npm version 5.6.0，The following dislocation occurred
```
ERROR in ./node_modules/_js-utils@0.0.0@js-utils/avatar/index.js 15:52
    Module parse failed: Unexpected token (15:52)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```
image
I don't know why TS syntax is JS file？
[update rename index.js to index.ts](https://github.com/jitsi/js-utils/pull/36)
i install node 8.11.3 version The error disappeared
I think it is necessary to add a node version to the novice

### CODE REVIEW

**Comment by daxiondi** [comment]
@damencho

**Comment by saghul** [comment]
That is flow type annotation syntax. Arguably unnecessary, but should be harmless.

What steps are you following exactly to get this error?

**Comment by daxiondi** [comment]
> That is flow type annotation syntax. Arguably unnecessary, but should be harmless.
> 
> What steps are you following exactly to get this error?

you use node version>=10,Execute NPM install and you will get this error

**Comment by daxiondi** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Do I need to sign an individual https://jitsi.org/icla Is it necessary to be a jitsi contributor? I want to spend a lot of time contributing to jitsi

**Comment by daxiondi** [comment]
> That is flow type annotation syntax. Arguably unnecessary, but should be harmless.
> 
> What steps are you following exactly to get this error?

I use node v10.15.3

**Comment by daxiondi** [comment]
I think this has something to do with the version of flow bin. If I change the version of flow bin to 0.95.1, you can ```npm insall``` normally on node v10.15.3. Please look at this [pr](https://github.com/jitsi/js-utils/pull/36/commits/3b55733fd4b0a780c61c3c027099e56d3df7a118), so I think this update README.md PR is more necessary to avoid more people encounter such problems as me. I have signed our cla（ https://jitsi.org/icla 。 Can you help me merge?

**Comment by daxiondi** [comment]
@saghul

**Comment by daxiondi** [comment]
@saghul

**Comment by saghul** [comment]
Do you see the problem with Node 12 and npm 6? We require those these days (I just realized we may have not mentioned it in this repo though).

**Comment by daxiondi** [comment]
> Do you see the problem with Node 12 and npm 6? We require those these days (I just realized we may have not mentioned it in this repo though).

I see your PR, so your solution is to delete the flow bin. In fact, I don't think it is necessary to add a supported node version in readme

**Comment by saghul** [comment]
Ah, right, that's in a different project so I was confused. I'll reply to you there.

**Comment by daxiondi** [comment]
Look forward to your reply and merge this pr

**Comment by daxiondi** [comment]
It has been modified as you said. Do you have any questions?

**Comment by daxiondi** [comment]
@saghul You can have a look when you have time

**Pull request merged**
