### PR TITLE
feat(force-mute): Implement force-mute functionality

### PR DESCRIPTION
**Pull request by gimre**
This PR is part of a series of PRs in multiple repositories to enable force-mute functionality in jitsi meetings:
- https://github.com/jitsi/jicofo/pull/604
- https://github.com/jitsi/jitsi-meet/pull/7779
- https://github.com/jitsi/lib-jitsi-meet/pull/1329

### CODE REVIEW

**Review by damencho — CHANGES_REQUESTED** [review]
Can you please first fix the lint errors.

**Comment by gimre** [comment]
rebased and fixed

**Comment by saghul** [comment]
That package-lock change sounds suspicious. Did you use Node 12 / npm 6?

**Comment by gimre** [comment]
@saghul oh, that is unintentional, i am using node 14 / npm 7 - will make it go away

**Comment by damencho** [comment]
Moving forward we decided to take another approach with it https://github.com/jitsi/lib-jitsi-meet/pull/1581

**Pull request closed without merging**
