### PR TITLE
Ff no media

### PR DESCRIPTION
**Pull request by hristoterezov**

### CODE REVIEW

**Comment by saghul** [comment]
Why are we disabling P2P on Firefox? Can you at least describe why on the commit message?

**Comment by gpolitis** [comment]
Hola Saul! this should have never been activated because sdp-interop does not support FF as the offerer https://github.com/jitsi/sdp-interop/issues/4. Hristo did some git archaeology and FF p2p was wrongfully enabled around a year ago. I agree we should document this.

**Comment by hristoterezov** [comment]
@saghul See the description of the commit that disables it:

> Currently P2P won't succeed on FF because it's not supported by
> sdp-interop.

**Comment by saghul** [comment]
@gpolitis But does it support it as the answerer?

@hristoterezov I think it needs some more background, like what @gpolitis said.

**Comment by gpolitis** [comment]
>  But does it support it as the answerer?

Yeah, which is the normal use-case in the non-P2P scenario.

**Comment by saghul** [comment]
> Yeah, which is the normal use-case in the non-P2P scenario.

Well, In P2P one has to be the offerer and one the answerer. Something I discussed with someone some time ago (maybe Emil?) was to support asymmetric P2P: that is, support P2P as long as it's the other party who sends the offer. Edge suffers from the same problem.

Good to know, at any rate!

**Pull request merged**
