### PR TITLE
Fix Error In Documentation on LOCAL_STATS_UDATED event

### PR DESCRIPTION
**Pull request by WesUnwin**

### CODE REVIEW

**Comment by WesUnwin** [comment]
Hello, if I fix the conflicts that have now occured, will this ever get merged? 

It's simply a fix to a typo, should be non-controversial.

Are you accepting contributions from others?  This has been open for almost a year.

**Comment by saghul** [comment]
This document got moved to the handbook, sorry for the trouble :-/ Any chance you could PR your changes there?

**Comment by WesUnwin** [comment]
@saghul thanks, have replicated this PR against the handbook repo:

https://github.com/jitsi/handbook/pull/163

**Comment by saghul** [comment]
Cheers!

**Pull request closed without merging**
