### PR TITLE
feat: allow to set the receiver video constraints per endpoint

### PR DESCRIPTION
**Pull request by jienco**
This allows for flexible quality management.

However for this to work, a fix is needed in videobridge too (see jitsi/jitsi-videobridge#1458)

Issue #1175

### CODE REVIEW

**Comment by jienco** [comment]
Signed CLA

**Comment by dilbert007** [comment]
This will be a very good help, thank you for this contribution.

We hope to have it up and running soon.

**Comment by dilbert007** [comment]
This will be a very good help, we hope to have it up and running soon.
Thank you for this contribution and hard work.

**Comment by zWaR** [comment]
@sapkra @bgrozev I landed here by reading this https://github.com/jitsi/jitsi-videobridge/issues/1458 What are your plans with this PR? We're trying to decide how to go about client triggered video constrains as well. This seems like a possibility, but  we'd like to see which direction you're going to go with it.

**Comment by jallamsetty1** [comment]
Closing this PR as it has been implemented already.

**Comment by jienco** [comment]
Thanks for the work in the implementation @jallamsetty1

**Pull request closed without merging**
