### PR TITLE
A stepping stone towards TypeScript

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by sapkra** [comment]
@saghul We fixed several issues in the handcrafted types. I have not checked if you are already using them but it would be great to have them in the repo instead. You can find them here:

https://github.com/sapkra/lib-jitsi-meet/tree/typescript_type_definitions

**Comment by saghul** [comment]
I picked them from the PR which was open. Thanks for the pointer, I'll look at yours and check!

**Comment by sapkra** [comment]
@saghul I updated the types to the latest release (6173) and moved them to this repo:
https://github.com/lynoapp/lib-jitsi-meet

**Comment by saghul** [comment]
Excellent, thanks! I hope to push this one forward next week.

**Comment by nightvisi0n** [comment]
Really looking forward to this, thanks for the work @saghul!

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by sapkra** [comment]
@saghul I have also updated them now in my repo to match v6433. You can compare them if you want. There might be some improvements.

**Comment by saghul** [comment]
Will do!

**Comment by sapkra** [comment]
@saghul Updated them again for v6689.

**Review by Calinteodor — APPROVED** [review]

**Pull request merged**
