### PR TITLE
ref(ts) remove todo on already converted imports

### PR DESCRIPTION
**Pull request by NewEraCracker**

### CODE REVIEW

**Comment by saghul** [comment]
@garyhuntddn any objections?

**Comment by garyhuntddn** [comment]
I think I've got a very similar PR in the queue - go ahead with whichever comes first - probably this one as you're in front of it :-)

My plan is to do a full review of the .spec.ts files once all the merges are in place.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Ah, I think it overlaps with https://github.com/jitsi/lib-jitsi-meet/pull/1935, which is more complete. I'll merge that first.

**Comment by saghul** [comment]
Can you rebase, just in case, @NewEraCracker ?

**Comment by NewEraCracker** [comment]
@saghul done.

**Review by saghul — APPROVED** [review]

**Pull request merged**
