### PR TITLE
Shuffle ICEServers for loadbalancing

### PR DESCRIPTION
**Pull request by psi-4ward**
Improve traffic loadbalancing when using multiple turnservers

https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/pc/ice_server_parsing.cc#299

### CODE REVIEW

**Comment by saghul** [comment]
@psi-4ward Can you please sign the CLA?

**Comment by psi-4ward** [comment]
Did it already. I'm Christoph Wiechert

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by fippo** [comment]
I don't think that is somethat that should be done in the client but rather mod_turncredentials.
And one typically uses a DNS hostname in a round-robin fashion so this shouldn't be required at all?

**Comment by saghul** [comment]
> I don't think that is somethat that should be done in the client but rather mod_turncredentials.
> And one typically uses a DNS hostname in a round-robin fashion so this shouldn't be required at all?

We allow an arbirtrary number of STUN / TURN servers to be specified via config, so I'd ssay this is a good idea overall. It will not impact those who use a single one with other types of load balancing (as we do on meet.jit.si) but it will help those who lisst more than one server there.

**Comment by psi-4ward** [comment]
DNS RR Setup is bit more complicated - think of certificate exchange.

Next: Whats the behavior when DNS resolvs to dead/faulty Coturn? ICE does not have alternative candidates in this case.

**Comment by awlx** [comment]
We are running (@FreifunkMUC) this patch on https://meet.ffmuc.net and for the first time all our three turnservers see traffic. I added a graph where you can clearly see that it makes a difference.

Screenshot 2020-05-12 at 10 20 01

**Comment by fippo** [comment]
> Next: Whats the behavior when DNS resolvs to dead/faulty Coturn? ICE does not have alternative candidates in this case.

Specifying multiple turn servers like that isn't a solution to that, it will generate relay candidates for each of them (you can see that in chrome://webrtc-internals) and increases the ice processing time. See the warning Firefox adds when you attempt to use more than four servers.

**Comment by nils-ohlmeier** [comment]
I would suggest that rotating between multiple TURN servers should better get implemented in the browser endpoint. We are happy to take patches for that into Firefox :-)

It makes sense to specify let's two different TURN server with different DNS domains for redundancy purposes (in case DNS for one domain fails or the host goes down etc). But just specifying multiple TURN servers within the same domain just slows things down. And without any randomizing in the browser endpoints only slows things down as the ICE stacks are trying to gather relay candidates from all until they have found a working candidate pair.

**Pull request merged**
