### PR TITLE
Avoid finally in promise chain. Log error if error happen in _l_lastVideoSenderUpdatePromise.

### LINKED ISSUE #2464: _lastVideoSenderUpdatePromise.finally is not a function
I got this error from react-native:
ERROR  [TypeError: this._lastVideoSenderUpdatePromise.finally is not a function (it is undefined)]

image

### PR DESCRIPTION
**Pull request by Romick2005**
Fixes #2464 _lastVideoSenderUpdatePromise.finally is not a function issue. Add more information about occurred errors.

### CODE REVIEW

**Comment by saghul** [comment]
What environment are you running in? Is Promise.prototype.finally not defined there?

**Comment by Romick2005** [comment]
> What environment are you running in? Is Promise.prototype.finally not defined there?

react-native

**Comment by saghul** [comment]
Then you need to apply the promise finally polyfill.

**Comment by Romick2005** [comment]
> Then you need to apply the promise finally polyfill.

But this pr allow us to see errors also. And this is the only place where we can have more environments covered. Wouldn't it be better? Also this will cover some case with UnhandledPromiseRejection. So for example:
```
const p = Promise.reject(new Error('BOOM'));
p.catch(() => {});
p.finally(() => {});
```
will throw UnhandledPromiseRejectionWarning
`(node:22503) UnhandledPromiseRejectionWarning: Error: BOOM at Object.<anonymous> `

But this:
```
const p = Promise.reject(new Error('BOOM'));
p.catch(() => {}).finally(() => {});
```

So it is not also about polyfils, but for general code reliability.
@saghul What do you think?

**Comment by saghul** [comment]
Error in that function can happen and are ok to ignore, hence the finally.

While what you say is generally good advice, it doesn't need to be followed in every case.

**Comment by Romick2005** [comment]
Is this a good case to kill two rabbits with one shot? Allow easy react-native integration and have proper error handling and logs?

I do not agree with you. So I will patch it, sorry.

**Pull request closed without merging**
