### PR TITLE
Set the FPS constraints only when video has been requested

### PR DESCRIPTION
**Pull request by dmurtari**
Since FPS only applies when video is requested, move this block to where the rest of the video constraints are applied.

### CODE REVIEW

**Comment by dmurtari** [comment]
I believe our organization has already signed the CLA (@dwilson6 will be able to verify).

**Comment by dwilson6** [comment]
Yes, we have signed the CLA

**Comment by dwilson6** [comment]
@bgrozev any problems with this one?  I'm trying to get some of our older PRs merged to make it easier to pull in new versions of lib-jitsi-meet.

**Comment by bgrozev** [comment]
Jenkins ok to test

**Comment by bgrozev** [comment]
I don't understand this well enough to merge. Does it solve a problem for you? Does this not affect screen sharing, too?

With the code in the new position, the "if (!constraints.video)" block is unnecessary, so please remove it.

**Comment by dmurtari** [comment]
This solves an issue we were seeing with redundant permission requests in Firefox, when requesting video/audio together with FPS constraints on the video. Since the behavior in `obtainAudioAndVideoPermissions()` is to split a video/audio GUM request into two separate requests for video and audio, we were seeing the FPS constraints passed in to the audio requests. This caused Firefox to prompt for both video/audio instead of just audio since the current behavior is to add back the video constraint if it does not exist when the FPS constraint is set, even if only audio is being requested (I hope that scenario makes sense). 

Screen sharing FPS isn't impacted, so should still be 3. 

I think I'm missing the `if (!constraints.video)` that you're referring to? There was one in the FPS block originally but I did get rid of that one.

**Comment by bgrozev** [comment]
> I think I'm missing the if (!constraints.video) that you're referring to?

Yeah, I must have misread, sorry.

**Comment by bgrozev** [comment]
Thanks for the fix!

**Comment by dmurtari** [comment]
No problem, thank you!

**Pull request merged**
