### PR TITLE
remove unused config parameters

### PR DESCRIPTION
**Pull request by TheGor1lla**

### CODE REVIEW

**Comment by saghul** [comment]
If anything, we should probably clarify the comment above saying that it's not necessary because we proxy the connections.

**Comment by TheGor1lla** [comment]
We are currently trying to get token authentication to work with out setup.  
Following the readme "Also check if client to server encryption is enforced. If not then token authentication won't work:" this part reads that the encryption must be set to true.  
If  I correctly read what @saghul said  this part is irrelevant? If so shouldnt this part of the doc be removed?

**Comment by damencho** [comment]
That setting is irrelevant to tokens, I think. So I don't see why not removing it ...

**Comment by saghul** [comment]
> That setting is irrelevant to tokens, I think. So I don't see why not removing it ...

Agreed.

**Comment by TheGor1lla** [comment]
Checked that it tokens work with either true/false to the mentioned parameter and removed the specific lines from the documentation

**Pull request merged**
