### PR TITLE
Export TRACK_ERROR_TO_MESSAGE_MAP so it can be accessed outside the library.

### PR DESCRIPTION
**Pull request by veselinovicst**
This refers to [issue](https://github.com/jitsi/jitsi-meet/issues/8919).

### CODE REVIEW

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by damencho** [comment]
Have you signed the CLA, cause I cannot find a match, thanks?

**Comment by damencho** [comment]
Hum, @veselinovicst seems I mislead you ... seems this mapping already exists and some of those are translated:
https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/devices/middleware.js#L35
And probably this is just missing in the pre-join screen, can you take a look at that?

**Comment by veselinovicst** [comment]
> Have you signed the CLA, cause I cannot find a match, thanks?

Hey, I signed using different email: stefanveselinovic

**Pull request closed without merging**
