### PR TITLE
feat(FirefoxSimulcast): move option to testing group

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
Documented in https://github.com/jitsi/jitsi-meet/pull/1806

@gpolitis @bbaldino can you PTAL?

**Comment by saghul** [comment]
The code is already in, so I guess we might as well have it proper, right?

**Comment by bbaldino** [comment]
well i was about to revert it all today, but i think i'm gonna push forward with it.  but still not sure it's worth documenting in its current state.

**Comment by saghul** [comment]
But you already merged the PR which documents this option 😮

**Comment by bbaldino** [comment]
yeah, didn't think about this until after.  i agree we should either also merge this or not merge this and revert the other.  what do you think with regards to the policy of when a feature flag should be documented, even in the 'testing' section?  do you think something in this state qualifies?

**Comment by saghul** [comment]
I'm not 100% sure of the state, but IIRC I read something about it being experimental (please do correct me if I'm wrong here) hence why I thought it belongs in testing.

**Pull request merged**
