### PR TITLE
fix: use correct jsdoc types for params and methods

### PR DESCRIPTION
**Pull request by sapkra**

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by sapkra** [comment]
@saghul I'm still unsure how the workflow at 8x8 is. I would be happy if you could help me out here. ❤️
1. Review PR
2. Approve PR
3. Jenkins Test
4. ?

e.g. how can it happen that [11 PRs (just in this repo) are approved](https://github.com/jitsi/lib-jitsi-meet/pulls?q=is%3Apr+is%3Aopen+review%3Aapproved) for many months and are still not merged or closed yet?

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
> @saghul I'm still unsure how the workflow at 8x8 is. I would be happy if you could help me out here. ❤️
> 
> 1. Review PR
> 
> 2. Approve PR
> 
> 3. Jenkins Test
> 
> 4. ?
> 
> 
> 
> e.g. how can it happen that [11 PRs (just in this repo) are approved](https://github.com/jitsi/lib-jitsi-meet/pulls?q=is%3Apr+is%3Aopen+review%3Aapproved) for many months and are still not merged or closed yet?

That's how it should work. But we are humans and sometimes forget 😞 

I'll setup stalebot to get reminded at least.

**Pull request merged**
