### PR TITLE
introduce declaration files for @jitsi/js-utils and @jitsi/logger

### PR DESCRIPTION
**Pull request by garyhuntddn**
These are only the bits I've needed so far - I'm sure there will be plenty more types to be added

### CODE REVIEW

**Comment by saghul** [comment]
How about we add those to the respective projects? We can cut a new release is necessary, in fact they are automated on every PR merge.

**Comment by garyhuntddn** [comment]
That would be better wouldn't it - we can auto-generate like we do with the auto ones in this lib

Are we able to publish NPMs? e.g. @types/jitsi/js-utils

**Comment by garyhuntddn** [comment]
To use the same technique would we need to move to webpack etc? we'll need to introduce tsc and a tsconfig.json

**Comment by garyhuntddn** [comment]
Just a quick update on this one - we're very likely going to add the types directly within the NPM packages themselves - so this PR will most likely be abandoned.

**Comment by saghul** [comment]
Yeah, I'd say we do that.

**Pull request closed without merging**
