### PR TITLE
Fix watchrtc consecutive call issue

### PR DESCRIPTION
**Pull request by subhamcyara**
Following PR contains the following changes :
1. Update watchRTC SDK version to 1.38.2
2. remove `persistentEnd` call to fix web socket connect/disconnect when conducting consecutive calls.

### CODE REVIEW

**Comment by saghul** [comment]
So is it no longer necessary to make that API call?

**Comment by subhamcyara** [comment]
Yes. We do not require that API call with new changes within our sdk. It helps to curb unnecessarily connect/disconnect (or reconnect) of websocket connections for calls.

**Review by saghul — DISMISSED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
Ops this fell trough the cracks due to the holydays. Can you please give it a rebase?

**Comment by subhamcyara** [comment]
Hi, I think I did a mistake while merging. I rectified and seems okay now. Please let me know if something seems off.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Pull request merged**
