### PR TITLE
feat(compute-pressure) monitor cpu pressure

### PR DESCRIPTION
**Pull request by mihhu**

### CODE REVIEW

**Comment by mihhu** [comment]
> Hi, thanks for your contribution! If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

CLA signed

**Comment by saghul** [comment]
Interesting choice, adding this to LJM instead of doing it in JM. Any reason for it? Generally speaking I _think_ this might fit better on the latter.

While being in a conference is the main activity, joining / leaving breakout rooms should likely not trigger attaching / detaching from the observer, I see this more like a global thing.

**Comment by mihhu** [comment]
> Interesting choice, adding this to LJM instead of doing it in JM. Any reason for it? Generally speaking I _think_ this might fit better on the latter.

I thought of making it available for those who use only LJM too. 

> While being in a conference is the main activity, joining / leaving breakout rooms should likely not trigger attaching / detaching from the observer, I see this more like a global thing.

So should I drop this PR and move the observer in JM?

**Comment by saghul** [comment]
> I thought of making it available for those who use only LJM too.

It's not a bad idea, and the line is blurry indeed, but since we currently don't do anything other that fire an event IMHO it's better suited for JM.

> So should I drop this PR and move the observer in JM?

I think so yeah.

**Pull request closed without merging**
