### PR TITLE
Transcriptions

### PR DESCRIPTION
**Pull request by nikvaessen**
Adds a transcription module 

The transcription module currently used a Sphinx server to send the audio to:
https://github.com/jitsi/Sphinx4-HTTP-server

This code requires the URL of the server to be set in config.js of Jitsi Meet as 
`sphinxURL: "<URL here>"`

### CODE REVIEW

**Comment by nikvaessen** [comment]
Jenkins add to whitelist

**Comment by damencho** [comment]
Adding to whitelist needs to be done by an admin, otherwise everybody can add themselves and run their code.
Jenkins: add to whitelist

**Comment by bgrozev** [comment]
Jenkins ok to test

**Comment by nikvaessen** [comment]
I reset the branch to "88235aa" and added the other changes again, so the new commit should only contain relevant code changes

**Comment by bgrozev** [comment]
A few comments with regard to the glue code in JitsiConference and JitsiMeetJS:

1. Why do we need the transcriberHolder if we can access the transcriber object from the JitsiConference object.
2. Why do we store the audioRecorder in JitsiConference?
3. The sphinx service will throw an error unless there's a global 'config' object with the needed property. I suspect that this is why tests are failing.
4. I don't see where the new tracks created by the library are handled (while the transcriber/recorder is running)

I would suggest that we remove the transcriberHolder and the additional code in JitsiMeetJS, and remove the creation of a recorder/transcriber instance with JitsiConference. Instead, add a getTranscriber() method to JitsiConference, which will create an instance if necessary.

**Comment by nikvaessen** [comment]
> 1. Why do we need the transcriberHolder if we can access the transcriber object from the JitsiConference object.


I added this because I didn't know how to acces it in the console otherwise.

> 2. Why do we store the audioRecorder in JitsiConference?

If we only create the transcriber object when it's requested, how would the transcriber get access to all the tracks, if it's not being stored in the audioRecorder from the start? Also, when a "removed track event" happens in JitsiConferenceEventManger, it needs to tell the audioRecorder that.  
 

> 3.The sphinx service will throw an error unless there's a global 'config' object with the needed 
> property. I suspect that this is why tests are failing.
> 

I changed it so it now just logs the error instead of throwing it, let's see if the test passes now. 

>  4. I don't see where the new tracks created by the library are handled (while the transcriber/recorder is running)


I forgot to write these methods. They should now be commited.

**Comment by bgrozev** [comment]
Thanks for addressing these, Nik.

> If we only create the transcriber object when it's requested, how would the transcriber get access to all the tracks, if it's not being stored in the audioRecorder from the start?

I was thinking that the code which initializes the transcribed will loop through the existing tracks and add them the the transcriber. The recorder can be private to the transcriber.

> Also, when a "removed track event" happens in JitsiConferenceEventManger, it needs to tell the audioRecorder that.

If we only initialize a recorder/transcriber if one is requested, this doesn't need to be handled specially -- if there is an instance, call removeTrack, otherwise don't.

**Pull request merged**
