### PR TITLE
fix(build) exclude generated types file from TSC build

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Hum `2023-12-15T21:38:38.218Z [modules/xmpp/strophe.util.js] <Ra.yt.Strophe.log>:  Strophe: error: e is not a function error: e is not a function
`

**Comment by damencho** [comment]
```
2023-12-15T21:38:38.203Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by client
2023-12-15T21:38:38.203Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Skip close handler, channel instance is not equal to stored one
2023-12-15T21:38:38.205Z [modules/e2ee/OlmAdapter.js] <Zr._onParticipantLeft>:  Participant 54ee48da left
2023-12-15T21:38:38.208Z [conference.js] <ti.<anonymous>>:  USER 54ee48da LEFT: [object Object]
2023-12-15T21:38:38.209Z [modules/e2ee/OlmAdapter.js] <Zr._onConferenceLeft>:  Conference left
2023-12-15T21:38:38.218Z [modules/xmpp/strophe.util.js] <Ra.yt.Strophe.log>:  Strophe: TypeError: e is not a function
    at https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:721749
    at Array.forEach (<anonymous>)
    at ps.clean (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:721737)
    at ti.o (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:722387)
    at o.emit (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:353407)
    at ps.onPresenceUnavailable (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:712003)
    at gs.onPresenceUnavailable (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:724607)
    at Handler.run (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:494679)
    at https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:503090
    at Array.reduce (<anonymous>)
    at https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:503014
    at Object.forEachChild (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:487441)
    at j.Connection._dataRecv (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:502950)
    at e._onRequestStateChange (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:521740) TypeError: e is not a function
    at https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:721749
    at Array.forEach (<anonymous>)
    at ps.clean (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:721737)
    at ti.o (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:722387)
    at o.emit (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:353407)
    at ps.onPresenceUnavailable (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:712003)
    at gs.onPresenceUnavailable (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:724607)
    at Handler.run (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:494679)
    at https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:503090
    at Array.reduce (<anonymous>)
    at https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:503014
    at Object.forEachChild (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:487441)
    at j.Connection._dataRecv (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:502950)
    at e._onRequestStateChange (https://oracle-prtorture.jitsi.net/libs/lib-jitsi-meet.min.js?v=139:2:521740)
```

**Comment by saghul** [comment]
WTF?! Not sure how that can be related to this PR 😮

**Comment by DanielMcAssey** [comment]
That shouldn't be related to this, right?

**Comment by saghul** [comment]
Not to this PR, but yes to the refactor, we missed a couple of spots where we needed cancellable listeners.

**Comment by DanielMcAssey** [comment]
Ah my bad! Thought I caught them all

**Comment by saghul** [comment]
No worries!

**Pull request merged**
