### PR TITLE
feat(xmpp) remove support for the deprecated options.bosh

### PR DESCRIPTION
**Pull request by saghul**
> 4 years seems like ample time :-)

### CODE REVIEW

**Comment by damencho** [comment]
Will it work with default config.js?
https://github.com/jitsi/jitsi-meet/blob/8a2e4bc6281ee2d7a0602d359a03c8dc9c2c34e0/config.js#L49

**Comment by damencho** [comment]
I think we handle it in jitsi-meet, so maybe its good.

**Comment by damencho** [comment]
I wonder whether the lib-jitsi-meet users are using the serviceUrl thingy ...

**Comment by paweldomas** [comment]
> I wonder whether the lib-jitsi-meet users are using the serviceUrl thingy ...

What I'd suggest is to throw an error with a meaningful message which makes fixing it a breeze:
```
if (options.bosh && !options.serviceUrl) {
  throw new Error('The "bosh" option is no longer supported, please use "serviceUrl" instead');
}
```

**Comment by saghul** [comment]
Updated PTAL!

**Review by paweldomas — APPROVED** [review]

**Pull request merged**
