### PR TITLE
fix: Updates strophe to 1.4.0.

### PR DESCRIPTION
**Pull request by damencho**
That fixes some websocket disconnect issues. Introduces option to use strophe in worker.

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by damencho** [comment]
We should update first strophejs-plugin-stream-managemen ... thanks for the tip @paweldomas

**Comment by damencho** [comment]
Well tests of strophejs-plugin-stream-management fail and also the PR tests all failed, will need to revisit later.

**Comment by Neustradamus** [comment]
@paweldomas: Have you looked?

**Comment by damencho** [comment]
This cannot be merged before exploring the stream management tests and fix those.

**Comment by Neustradamus** [comment]
@damencho: It is for this that I have requested to @paweldomas to look...
But why have you closed it?

**Comment by damencho** [comment]
Cause I had open it, I know the state of it and I know the ongoing work and I think that is not a priority for now and this PR itself has nothing in it, the work needs to be done in another place ... many reasons.

**Comment by Neustradamus** [comment]
@damencho: OK but there is not the "Issues" section in the fork.
Can you see with @paweldomas to do a PR into the main repository?
- Main: https://github.com/strophe/strophejs-plugin-stream-management
- Fork: https://github.com/jitsi/strophejs-plugin-stream-management

**Comment by saghul** [comment]
Here we go again. Why don't you stop telling people how to work?

**Comment by Neustradamus** [comment]
@saghul: I think that we can talk together, normally no?
- Issues section is not here: https://github.com/jitsi/strophejs-plugin-stream-management
- It is linked to this ticket

Do you want to solve problems or keep problems?

Like @damencho have said: "That fixes some websocket disconnect issues. Introduces option to use strophe in worker."
- https://github.com/jitsi/lib-jitsi-meet/pull/1315#issue-484012752

I think that you want to have a best stability/security/... in Jitsi products, like me, no?

**Comment by paweldomas** [comment]
> Like @damencho have said: "That fixes some websocket disconnect issues. Introduces option to use strophe in worker."

We were discussing it with Damyan offline some time ago and those "some websocket disconnect" issues are not important.
The fact is that this update breaks stream resumption tests and hence requires more work that is not going to happen now.

Merging the fork upstream is not easy as I left the build machinery (which I don't fully understand) in a slightly modified state which I don't know how to fix.

**Comment by Neustradamus** [comment]
@paweldomas: Thanks for your reply.
I understand, I hope that you will find the time to do it.
When you will solve problems, please create a PR to have your improvements in the main code...

**Pull request closed without merging**
