### PR TITLE
Update webrtc-adapter v7.7.1 (fix Safari)

### PR DESCRIPTION
**Pull request by yulllll**
Fix Safari RTCSessionDescription.sdp readonly
Based on https://bugs.chromium.org/p/chromium/issues/detail?id=1186456&

### CODE REVIEW

**Comment by jallamsetty1** [comment]
Thanks @yulllll for the PR, have you been able to sign our CLA ?

**Comment by saghul** [comment]
package-lock wasn't updated.

**Comment by saghul** [comment]
Also, we don't need the CLA for this.

**Comment by yulllll** [comment]
> package-lock wasn't updated.

fixed

**Comment by saghul** [comment]
Jenkins please test this please.

**Review by saghul — APPROVED** [review]

**Pull request merged**
