### PR TITLE
fix(E2EE): potential race when en-/disabling

### PR DESCRIPTION
**Pull request by nils-ohlmeier**

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by nils-ohlmeier** [comment]
@saghul @damencho did my change introduce/uncover a new test failure, or is this some kind of known problem in the sendSessionAccept test?

**Comment by NewEraCracker** [comment]
LOL. About test: same that I had described on #2069 and fix at #2071

**Comment by saghul** [comment]
Thanks @NewEraCracker , merged! @nils-ohlmeier can you pl rebase so the tests run with  the new dependencies?

**Comment by nils-ohlmeier** [comment]
Thank you @NewEraCracker your patch indeed fixes the test failure!

@saghul could you please stamp again?

**Comment by saghul** [comment]
Something looks off, there are 3 commits in this PR, 2 of which are already in master.

**Comment by nils-ohlmeier** [comment]
> Something looks off, there are 3 commits in this PR, 2 of which are already in master.

Not sure how I managed to screw that one up. It should look better now.

**Review by saghul — APPROVED** [review]

**Pull request merged**
