### PR TITLE
e2ee: decode static black frame for decryption errors

### PR DESCRIPTION
**Pull request by fippo**
similar to #1095 use a black keyframe instead of displaying a potentially
unencrypted stream. This was again captured with a modified version of
the webrtc sample, additional logging and a resolution of 320x180

### CODE REVIEW

**Comment by fippo** [comment]
I think we need a different approach but this is an ok stop-gap.

The better approach would be to emit a signal about the decryption status and set it to false in case of errors. I would prefer to do that after workers though.

**Comment by fippo** [comment]
@saghul also assuming we are now tagging commits with e2ee instead of hips since we are no longer hiding :-)

**Comment by saghul** [comment]
Jenkins, add to whitelist.

**Comment by saghul** [comment]
Jenkins, please test this please.

**Pull request merged**
