### PR TITLE
Typescript implementation of JitsiTrackEvents

### PR DESCRIPTION
**Pull request by garyhuntddn**

### CODE REVIEW

**Comment by garyhuntddn** [comment]
This replaces the original we had which had merge conflicts

**Comment by saghul** [comment]
No enum on this one?

**Comment by garyhuntddn** [comment]
Ha ha - and that’s why we do reviews :-)

good spot - I’m on my mobile and can’t see the option to convert to draft but I’ll fix if I have time tomorrow

**Comment by saghul** [comment]
Converted it to a draft :-)

**Comment by garyhuntddn** [comment]
That's all in place ready to check and merge

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Pull request closed without merging**
