### PR TITLE
fix: typos and jsdoc

### PR DESCRIPTION
**Pull request by NewEraCracker**
Some cosmetic things I noticed.

### CODE REVIEW

**Review by saghul — DISMISSED** [review]

**Review by saghul — APPROVED** [review]

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by NewEraCracker** [comment]
Looks like one of the recent changes has led to merge conflicts. Let me know if you wish me to rebase.

**Review by saghul — DISMISSED** [review]

**Comment by saghul** [comment]
Sorry about that. Can you rebase please?

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Review by saghul — APPROVED** [review]

**Pull request merged**
