### PR TITLE
Lipsync tests

### PR DESCRIPTION
**Pull request by paweldomas**
Adds config options required for lip-sync tests

### CODE REVIEW

**Comment by paweldomas** [comment]
Jenkins, test this again

**Comment by paweldomas** [comment]
Jenkins: ok to test again.

**Comment by paweldomas** [comment]
test again

**Comment by paweldomas** [comment]
test again, it must work this time

**Comment by damencho** [comment]
Jenkins: test this please

**Comment by paweldomas** [comment]
Jenkins: ok to test again.

**Comment by paweldomas** [comment]
Jenkins: ok to test again.

**Comment by damencho** [comment]
After fixing torture tests branch, Jenkins: ok to test again.

**Comment by paweldomas** [comment]
jenkins test this please

**Comment by paweldomas** [comment]
jenkins test this please

**Comment by paweldomas** [comment]
jenkins test this please(want 1 more pass)

**Comment by paweldomas** [comment]
jenkins test this please

**Comment by paweldomas** [comment]
jenkins test this please

**Comment by paweldomas** [comment]
jenkins test this please

**Comment by paweldomas** [comment]
jenkins test this please(just to be sure)

**Pull request merged**
