### PR TITLE
refactor(statistics): Remove unused code

### PR DESCRIPTION
**Pull request by hristoterezov**

### CODE REVIEW

**Comment by hristoterezov** [comment]
Agree!

**Comment by bgrozev** [comment]
I agree, and I think the jicofo code should go.

**Comment by bgrozev** [comment]
@hristoterezov What is the status on this?

**Comment by hristoterezov** [comment]
@bgrozev We still have to remove the code from jicofo. Then I'll rebase it and we can merge both.

**Comment by hristoterezov** [comment]
https://github.com/jitsi/jicofo/pull/144 removes the code from jicofo. There is code in jicoco that should  be also removed and maybe somewhere else but @gpolitis is working on that.

**Comment by lyubomir** [comment]
@hristoterezov, the automatic PR testing of this failed because of ESLint errors:

lib-jitsi-meet/modules/xmpp/xmpp.js
  1:14  error  '$msg' is defined but never used    no-unused-vars
  1:20  error  'Base64' is defined but never used  no-unused-vars

Do you have an idea how these got past the commit hook?

**Comment by hristoterezov** [comment]
@lyubomir Maybe I fixed it and forgot to add the changes before committing and the rebase didn't run eslint for sure. But I'm not 100% if this is the case. Sorry for these eslint errors.

**Pull request merged**
