### PR TITLE
sdp: remove remove(Session|Media)Lines

### PR DESCRIPTION
**Pull request by fippo**
removes two unused methods for mangling SDP.

### CODE REVIEW

**Comment by fippo** [comment]
they've been unused [even here](https://github.com/ESTOS/strophe.jingle/blob/master/strophe.jingle.sdp.js#L44) so are probably an artefact of earlier SDP munging things ;-)

**Comment by fippo** [comment]
ah... [used here](https://github.com/ESTOS/colibri.js/blob/master/colibri.js#L379). But that focus module is gone for a while.

**Comment by fippo** [comment]
@paweldomas i hear you pulled the shorter one ;-)

**Comment by hristoterezov** [comment]
Waiting for @paweldomas to approve since you requested a review from him. Otherwise I would merge :(

**Pull request merged**
