### PR TITLE
Bump minimum supported Chromium version to 72.

### PR DESCRIPTION
**Pull request by saghul**
Current stable is 86.

### CODE REVIEW

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by saghul** [comment]
Jenkins please test this please.

**Review by jallamsetty1 — APPROVED** [review]
LGTM Saul! I assume you are planning to update this https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/media/middleware.js#L167 when you bump the LJM commit in jitsi-meet.

**Comment by saghul** [comment]
> I assume you are planning to update this https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/media/middleware.js#L167 when you bump the LJM commit in jitsi-meet.

Yep, that;'s part of https://github.com/jitsi/jitsi-meet/pull/8045

**Pull request merged**
