### PR TITLE
Fix the variable name error.

### PR DESCRIPTION
**Pull request by aaftio**
Fix the variable name error.

### CODE REVIEW

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by aaftio** [comment]
Fix the variable name error.

**Comment by aaftio** [comment]
Why this change not commit into the master brach ? @saghul

**Comment by jallamsetty1** [comment]
Jenkins please test this please.

**Comment by jallamsetty1** [comment]
@aaftio, can you please sign our CLA if you haven't done so already ?

**Comment by aaftio** [comment]
> @aaftio, can you please sign our CLA if you haven't done so already ?

I have sign CLA already.

**Comment by sapkra** [comment]
@saghul @jallamsetty1  Can one of you merge this please? It's still a bug in the master branch.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Bummer, it's got a conflict now. I'll fix it when I'm front of a computer. Sorry this fell through the cracks :-/

**Comment by sapkra** [comment]
Merged into master with #1686.

**Pull request closed without merging**
