### PR TITLE
Prepare repository to publish to npm

### PR DESCRIPTION
**Pull request by sapkra**
Related: #484 

I thought about versioning but I'm still not happy with this solution.

Some ideas:
- `1.[jitsi_meet_tag].[numeric_tag]`
- `1.[jitsi_meet_tag].0` and `1.[jitsi_meet_tag].0-preview.[numeric_tag]`
- replace current versioning with semver

But I'm not sure how your tagging is working and defined. Is there a documentation about that e.g. for the numeric one like `819`?

### CODE REVIEW

**Comment by damencho** [comment]
819 is jenkins build id. 
My proposal will be to be consistent with the rest of the projects, like https://github.com/jitsi/jitsi-videobridge/blob/4b50618445a607298dadb1319d5a197397654692/resources/build_deb_package.sh#L31

**Comment by saghul** [comment]
Thanks for getting this started @sapkra! We had some internal discussions about this in the past, and currently the only blocking issue (that I'm aware of) is automation. We need to make sure that every merge to this repo results in a new release so we can then update Jitsi Meet.

As for versioning, I think we should start at 2.0 given that we are changing the package name, that's kinda a big deal.

Then what I proposed is to have the automation raise the patch level by 1 on every release, unless the previous one doesn't exist. This would be the case if you make a minor (or major change) as you'd bump the minor (or major, depending on the case) as part of the PR you send.

**Comment by sapkra** [comment]
Ok. I just had a lot of problems again using yarn. I think they are caching packages based on the version in the package.json which results in installing of old dependencies because the version is always 0.0.0.

To fix that I had to delete my yarn.lock file everytime I've ran yarn install or publish my own package. Because I couldn't see any progress on the official side I just published my own package and wanted to share my changes to push this forward.

I think it's s big deal to don't have an official package because someone else could publish the library to npm with adding some malicious code.

**Comment by saghul** [comment]
We have control over “lib-jitsi-meet “ and I believe nobody can publish under @jitsi/ without being part of the Jitsi org. Isn’t this right?

**Comment by sapkra** [comment]
Ok I see, but I think if we want to publish it regularly to npm it should be in the same organization like all the other packages published by jitsi. This would be the cleanest way in my opinion. The old package could be marked as deprecated.

**Comment by saghul** [comment]
Correct, we plan on publishing on @jitsi/ and deprecating the old one. The publication will be done by a CI.

**Comment by everflux** [comment]
I can't find the published npm artifacts, is this still ongoing?

**Comment by saghul** [comment]
Yes, the current world events have pushed this back, alas.

**Comment by sapkra** [comment]
@everflux You can use my package `@lyno/lib-jitsi-meet` if you want. I'm updating it regularly (usually for every stable release) until there is an official package.

**Comment by jordisala1991** [comment]
@sapkra are you still mainaining the `@lyno/lib-jitsi-meet`? It would be nice to have the latest releases of this package.

**Comment by sapkra** [comment]
@jordisala1991 I haven't had the time to update my cluster to the new version yet, so I haven't released the new version yet. But since you asked for it, I just did it now. I released the new version a few minutes ago, including the updated TypeScript type definitions which are automatically generated, so some are unfortunately missing.

**Comment by jordisala1991** [comment]
Thank you so much!

**Comment by sapkra** [comment]
Closing it for now. All my changes to it can be found here: https://github.com/lynoapp/lib-jitsi-meet

**Pull request closed without merging**
